### PR TITLE
Update nano teaser

### PR DESCRIPTION
**Pull request by pmrv**
Include a fix for plotting in the voila notebook.

@muh-hassani Will the new version show up on the workshop installation automatically after merging this?

### CODE REVIEW

**Comment by muh-hassani** [comment]
@pmrv, I think so.

**Comment by muh-hassani** [comment]
@pmrv, if your changes are complete. I can merge it to test it on the cluster.

**Comment by pmrv** [comment]
> @pmrv, if your changes are complete. I can merge it to test it on the cluster.

That would be great, thanks!

**Comment by muh-hassani** [comment]
@pmrv can you please log in to the server and check whether you have the latest version of your notebooks?

**Comment by pmrv** [comment]
Seems to have worked.  At least to last modified date shows two minutes ago and includes the changes.

**Pull request merged**
